### ISSUE TITLE
诗词文字显示重叠, is it a bug?

### ISSUE THREAD

**Issue by okcy1016** [chinese-poetry/poetry-calendar#1]
### 现场：
![image](https://user-images.githubusercontent.com/24411020/39691748-20cdacae-5211-11e8-9da1-12407b4b4333.png)
![image](https://user-images.githubusercontent.com/24411020/39691819-6c874646-5211-11e8-9690-d14cff35a305.png)
几乎大部分日期下的页面都有文本重叠的情况。

### 运行环境：
OS : Manjaro gnome.

浏览器: Chromium  Version 66.0.3359.117 (Official Build) Arch Linux (64-bit)

**Comment by jackeyGao** [comment]
好神奇的BUG

我还没有遇到过， 而且没有很快安装Manjaro操作系统的方式 。  

🤣

**Comment by okcy1016** [comment]
哇，您回复好快呀 (*＾v＾*)  。

不过，我觉得和使用不同的 Linux 发行版没有什么关系，可能是chromium的原因。
它代码更新频率很高。

**Comment by jackeyGao** [comment]
前端水平渣， 不知道从哪里下手修这个 bug， 话说 你是用 Manjaro 当主力开发机吗？  厉害了

**Comment by okcy1016** [comment]
是啊。
不过也没什么值得夸赞的，倒是您，
写的爬虫收集了古代诗歌，既凸显了技术实力、又为人类作出了贡献 (๑`･ᴗ･´๑)。

你看就知道您是位古文爱好者， 还会JS (　◠ ◡ ◠　) 。
